language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
script: 
  - jdk_switcher use oraclejdk8
  - mvn clean package
before_deploy:
  - ./release/tar_libs.sh
deploy:
  provider: releases
  api_key:
    secure: ZeUsSfW68AEglswXRIur1YXk+d2dbYAqAbrJbcsTpnp/yw/oAqnoGw/g79/AXE/fK2K3OStwKH73pnUm+1496n2iJbWAps1BheYnrhOV4DiDmkmK4rdEqV6fzfTL2EuLZPpM/rhpREbpibtM8VHTUKwrDKJ4+LpwdusSubvKbZ2PnhpTS6a8jBvVGdgxfzahSR4xEP5EOHCns7CerRh4toZgvQqQJt6W8cQXVeTYx3Vfrj2RqidLADa3bNxT/oisTw3nPR+YluPgYHfplsS1uwM0c7T0LGXvRwLnKjbtlhsQht4d/1IuX+qLO2hi1OoNihDAg5ZrvkqEGIelEkcvwQkJPnMVGKxb5ap01YgZpvUGZkpIQMK+Xi7/R5pde3WZhRV2a7B9Vg93rXoDuTLriHOYwgq5s6dScEk3Bh4AProtuVMhFM/UywCltIzrcwSpeciapUX8Tm+Xa2BfljK4QW6iHGiEAFj/YPXSI0Z+dvRFRMPDqvSTQB3sOTYOlkg19BjmiKdVkTfaLnEPrAU/7zu+CEFRJR3NgqnYYfx4Jkukc3VNoV/ubc71XMtDUtli8mIhoJChc2DVmLNMeZ1x7gyFAP1c+s9FiVXJC2IQXt9LPNY6ekOkG2fcdKOOky/VXuV9u1yeFe47HKFUgXQkrME2K+VyicAsq8QOUiv44Y0=
  file: kafka-connect-kinesis-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: vaski/kafka-connect-kinesis
