language: java
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
jdk:
- oraclejdk8
script:
- jdk_switcher use oraclejdk8
- mvn clean package
before_deploy:
- ./release/tar_libs.sh
deploy:
  provider: releases
  api_key:
    secure: nioNFgDM0ERimPD2Gc4FrordH7m7bb9HWkxQarSK5lWe7IG0JapG7SblnAPic8Ip1E+RMMxQx7W6H+3L44rKcwLLgLDfnJ+y93QYRFh9+jhtKThfypxE/uqqcQ1L10KuI9TuecxgfXrH1WaaQdQ4c5xH6K3P0IkYAxVQva6V/rhN7MnHMvB5D+rUnNC5Ok493rZ4g367YaYGyWVBg2eEdJQfUIdr0tzCRyOtAy1g6m506ZgM6JxzMt/+2iWexrZi76onHstNChmsrw54yBvQZhz2EsLKsqGPD68fGZND+Nh7vXEesiaiNVzGak4qOW/+v00ecXEN5AGteuv9QUAi54AiZObwJlzC3tVeook5RLAyx7s8iEeTfGxR3k/YP/Y8Fm0KpCVVhIauYn1sEfnNV5SMWq6gNQknGvGn8JmAndvTIN7geWDaA1CSEaMLf4bfqQ03NXjR3IBIyiExHHHQZrIuKF4PgzAk4F9XtNhiIKhiTJJ/esKetv9rU6gf/LWak1iGtNqNatv+rDmcCI3D4VKWKLxDEjoE+w70s0zdtYjgrpcZz7Mz476nblVZe8zUgN/hePKAbOeEdMOljIaJ9LhCH6GeDY/oYhgdr2P2ibBX+0D38NZireCxNwkdL5S9F41Z+dWriL53e3YIEClbyers1cevafNhmaPJgjSKHA4=
  on:q
    repo: vaski/kafka-connect-kinesis
env:
  global:
    secure: aoOSLzLrrct9Y2mNUFTipBurLGAR798krNIaXrcpTEmj5oro8yc99YE53iPpnGhDm1Bj3+VwQqucxChS7058Jtglym8R5OiLIvRXs6eDDNKshDk9sJ4Ab+rye2bHYa14QP5G0sjrQVQ4yVZLorFDgILtZDBM4D/PirLSE1GQ+rNH9Wo1H/NaqceWkfgcXUY3sF6elXhCV1Mi7WX0iRyYtwl1fIZQpMnbspl4GMPBpigJ8dZaQWDdRM6+FHUChYdo8hQxULywvHlWmZfl6x2sQ0GZoRCNBVa7VbW1IcuoaJ9beOkTfFWQuFHYSIBi5XxeR7UCIWv8TBeO/bIzhdlCvJdu5Kt3y52/AOQdXl3XrU5ep+PUqBbO008tUH6OMHuzRT15IomMl3+y/07/QNzQv+SNhTfhqRkQZbQGYGXuLCguW71hWfL5SdGLk4LLtgGw70+vKLFcTlOZbNisLsp2KhplQM3RSrUa4KEilnbIDFA0s565qPevZOyA/zL61QB7f6BpqIS7kAlAb/ByUmXZXZip8OAaCoToi3tN4D/i1dAr2MvPHGc+eGEOOrvpxJVBxmOwJecQqsbzReUbqX4mvhPKJJ1VQd+WW493GfIaeiy8gMEpZ1MdyLIeYz210jPqVgwmaELd3saH1w31IwPoj3wGxQg+BKUxYypcehJFR3c=
